# Generated by Django 3.1.2 on 2021-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_avatar_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='name',
            field=models.CharField(default='게임듀오인', max_length=20),
        ),
    ]
