# Generated by Django 3.1.2 on 2021-02-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AddField(
            model_name='messageroom',
            name='receiver_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messageroom',
            name='sender_read',
            field=models.BooleanField(default=False),
        ),
    ]
