# Generated by Django 3.1.2 on 2021-02-04 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_usergame'),
        ('message', '0003_auto_20210204_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='game_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='matching.game'),
        ),
    ]
