# Generated by Django 3.1.2 on 2021-02-04 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messageroom_game_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageroom',
            old_name='game_genre',
            new_name='game',
        ),
    ]
