# Generated by Django 3.1.2 on 2021-02-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20210204_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='game',
        ),
    ]
