# Generated by Django 3.1.2 on 2021-02-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_remove_messageroom_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='game_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
