# Generated by Django 3.1.2 on 2021-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_messageroom_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='receiver_consent',
            field=models.BooleanField(default=False),
        ),
    ]
