# Generated by Django 3.1.2 on 2021-02-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_messageroom_receiver_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageroom',
            name='sender_greeting',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
