# Generated by Django 3.1.2 on 2021-04-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_messageroom_sender_greeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageroom',
            name='sender_greeting',
        ),
    ]
