# Generated by Django 3.1.2 on 2021-04-13 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('genre', models.CharField(choices=[('FPS', 'Fps'), ('AOS', 'Aos'), ('MMORPG', 'Mmorpg'), ('SIMULATION', 'Simulation'), ('PUZZLE', 'Puzzle'), ('DEFENCE', 'Defence'), ('ADVENTURE', 'Adventure'), ('ACTION_ADVENTURE', 'Action Adventure'), ('HORROR', 'Horror'), ('CASUAL', 'Casual'), ('RHYTHM', 'Rhythm')], max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('game_photo', models.ImageField(upload_to='game/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_nickname', models.CharField(max_length=200)),
                ('is_random_agreed', models.BooleanField(default=True)),
                ('is_profile_agreed', models.BooleanField(default=True)),
                ('created_date', models.DateField(default=django.utils.timezone.now)),
                ('self_introduction', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matching.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
