// auth
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';
export const LOGOUT = 'LOGOUT';

// lol-matching
export const LOL_USER_GAME_SAVE_SUCCESS = 'LOL_USER_GAME_SAVE_SUCCESS'
export const LOL_USER_GAME_SAVE_FAIL = 'LOL_USER_GAME_SAVE_FAIL'
export const LOL_USER_GAME_UPDATE_SUCCESS = 'LOL_USER_GAME_UPDATE_SUCCESS'
export const LOL_USER_GAME_DELETE_SUCCESS = 'LOL_USER_GAME_DELETE_SUCCESS'

// Alert
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const SET_ERROR_ALERT = 'SET_ERROR_ALERT'
export const REMOVE_ERROR_ALERT = 'REMOVE_ERROR_ALERT'
