# Generated by Django 3.1.2 on 2020-11-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lolusergame',
            name='lol_lv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
