# Generated by Django 3.1.2 on 2020-11-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0002_auto_20201111_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lolusergame',
            name='main_champ_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
