# Generated by Django 3.1.2 on 2020-11-11 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0003_auto_20201111_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lolposition',
            name='usergame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lol_position', to='lolapi.lolusergame'),
        ),
        migrations.AlterField(
            model_name='lolprefermode',
            name='usergame',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lol_prefer_mode', to='lolapi.lolusergame'),
        ),
    ]
