# Generated by Django 3.1.2 on 2020-11-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0004_auto_20201111_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolusergame',
            name='region',
            field=models.CharField(choices=[('BR', 'Brazil'), ('EUN1', 'Europe Nordic And East'), ('EUW1', 'Europe West'), ('LA1', 'Latin America North'), ('LA2', 'Latin America South'), ('NA', 'North America'), ('OC1', 'Oceania'), ('RU1', 'Russia'), ('TR', 'Turkey'), ('JP1', 'Japan'), ('KR', 'Republic Of Korea')], default='KR', max_length=10),
        ),
        migrations.AlterField(
            model_name='lolposition',
            name='is_ad_possible',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Bad But Possible'), (2, 'Not Bad'), (3, 'So So'), (4, 'Good'), (5, 'Very Good')]),
        ),
        migrations.AlterField(
            model_name='lolposition',
            name='is_jungle_possible',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Bad But Possible'), (2, 'Not Bad'), (3, 'So So'), (4, 'Good'), (5, 'Very Good')]),
        ),
        migrations.AlterField(
            model_name='lolposition',
            name='is_mid_possible',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Bad But Possible'), (2, 'Not Bad'), (3, 'So So'), (4, 'Good'), (5, 'Very Good')]),
        ),
        migrations.AlterField(
            model_name='lolposition',
            name='is_sup_possible',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Bad But Possible'), (2, 'Not Bad'), (3, 'So So'), (4, 'Good'), (5, 'Very Good')]),
        ),
        migrations.AlterField(
            model_name='lolposition',
            name='is_top_possible',
            field=models.IntegerField(choices=[(0, 'Never'), (1, 'Bad But Possible'), (2, 'Not Bad'), (3, 'So So'), (4, 'Good'), (5, 'Very Good')]),
        ),
    ]
