# Generated by Django 3.1.2 on 2020-11-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0006_auto_20201111_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lolusergame',
            name='flex_rank',
            field=models.CharField(choices=[('UNRANKED', 'Unranked'), ('I', 'One'), ('II', 'Two'), ('III', 'Three'), ('IV', 'Four'), ('V', 'Five')], default='UNRANKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='lolusergame',
            name='solo_rank',
            field=models.CharField(choices=[('UNRANKED', 'Unranked'), ('I', 'One'), ('II', 'Two'), ('III', 'Three'), ('IV', 'Four'), ('V', 'Five')], default='UNRANKED', max_length=10),
        ),
    ]
