# Generated by Django 3.1.2 on 2020-11-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0007_auto_20201111_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lolusergame',
            old_name='perfer_style',
            new_name='prefer_style',
        ),
    ]
