# Generated by Django 3.1.2 on 2021-01-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lolapi', '0008_auto_20201118_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolusergame',
            name='mic',
            field=models.CharField(choices=[('MIC', 'Mic'), ('HEARING', 'Hearing'), ('RANDOM_MIC', 'Random Mic')], default='HEARING', max_length=10),
        ),
    ]
